cacheCapacity: 100 # korisnik
memtableSize: 100 # korisnik
memtableNum: 10 # korisnik
structureType: hashmap # korisnik
tokenNumber: 1000 # korisnik
tokenRefreshTime: 2 # korisnik
maxEntrySize: 1024
segmentSize: 65536 # korisnik
crcSize: 4 # korisnik
timestampSize: 8 # korisnik
compression: no # korisnik
tombstoneSize: 1 # korisnik
keySizeSize: 8 # korisnik
valueSizeSize: 8 # korisnik
crcStart: 0 # korisnik
maxLevels: 4 # korisnik
lsmMaxTables: 10 #korisnik
lsmMaxLevels: 4 #korisnik
scalingFactor: 2
compactionAlgorithm: leveled # korisnik
timestampStart: 4 # korisnik
tombstoneStart: 12 # korisnik
keySizeStart: 13 # korisnik
ValueSizeStart: 21 # korisnik
keyStart: 29 # korisnik
degreeOfDilution: 5 # korisnik
sstFiles: one # korisnik
lsmLeveledComp: 4 # korisnik
