cacheCapacity: 100 # korisnik
memtableSize: 10 # korisnik
memtableNum: 2 # korisnik
structureType: hashmap # korisnik
tokenNumber: 1000 # korisnik
tokenRefreshTime: 2 # korisnik
segmentSize: 65536 # korisnik
crcSize: 4 
timestampSize: 8 
compression: no # korisnik
tombstoneSize: 1 
keySizeSize: 8 
valueSizeSize: 8 
crcStart: 0 
lsmMaxTables: 5 #korisnik
lsmMaxLevels: 4 #korisnik
compactionAlgorithm: sizeTiered # korisnik
timestampStart: 4 
tombstoneStart: 12 
keySizeStart: 13 
ValueSizeStart: 21 
keyStart: 29 
degreeOfDilution: 5 # korisnik
sstFiles: one # korisnik
lsmLeveledComp: 4 # korisnik
